---

- name: Update System
  apt: update_cache=yes upgrade=yes

- name: install essential packages
  apt: name={{ item }} state=latest
  with_items:
    - htop
    - mc
    - screen
    - links
    - sudo
    - less
    - curl
    - git
    - drush
    - wget
    - mytop
