---
- name: Install backup and migrate
  shell: cd /var/www/{{ domain }}; drush dl -y backup_migrate

- name: Enable backup and migrate
  shell: cd /var/www/{{ domain }}; drush en -y backup_migrate

- name: download s3 library
  get_url: url='https://github.com/tpyo/amazon-s3-php-class/tarball/master' dest=/var/www/{{ domain }}/sites/all/libraries/s3.tar.gz

- name: extract s3 library
  shell: tar -xzf /var/www/{{ domain }}/sites/all/libraries/s3.tar.gz -C /var/www/{{ domain }}/sites/all/libraries/

- name: move s3 library
  shell: mv /var/www/{{ domain }}/sites/all/libraries/tpyo-amazon-s3-php* /var/www/{{ domain }}/sites/all/libraries/s3-php5-curl

- name: rm /var/www/{{ domain }}/sites/all/libraries/s3.tar.gz
  shell: rm -rf /var/www/{{ domain }}/sites/all/libraries/s3.tar.gz

- name: fix drupal permissions
  shell: chown www-data.www-data /var/www/{{ domain }}/sites/all/libraries/ -R

- name: fix drupal permissions
  shell: chmod -R 640 /var/www/{{ domain }}/sites/all/libraries/

- name: fix drupal permissions
  shell: find /var/www/{{ domain }}/sites/all/libraries/ -type d -exec chmod 750 {} \;

#Create a s3 backup profile with the name s3backup on the website and after that uncomment this
- name: Add cron job for s3 backup
  cron: name="s3backup" minute="0" hour="23" day="*" job="cd /var/www/{{ domain }} ; drush bam-backup archive s3backup"

- name: Add cron job for backup
  cron: name="normalbackup" minute="0" hour="22" day="*" job="cd /var/www/{{ domain }} ; drush bam-backup archive"
